USE INVENTORY_MANAGEMENT_DB;

CREATE TABLE VEHICLE_TYPE (
    VEHICLE_TYPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(30),
    MODEL VARCHAR(30)
);
 
CREATE TABLE VEHICLE (
    VIN VARCHAR(17) PRIMARY KEY,
    VEHICLE_TYPE_ID INT NOT NULL,
    COLOR VARCHAR(20),
    YEAR INT,
    MILEAGE DOUBLE,
    IMAGE VARCHAR(200),
    FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID)
);

CREATE TABLE VENDOR (
    VENDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENDOR_NAME VARCHAR(20),
    VENDOR_PHONE VARCHAR(15),
    VENDOR_EMAIL VARCHAR(30)
);
 
CREATE TABLE INVENTORY (
    INVENTORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    VIN VARCHAR(17) NOT NULL,
    VENDOR_ID INT,
    PRICE DOUBLE,
    FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN),
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);