USE INVENTORY_MANAGEMENT_SYSTEM;

CREATE TABLE VEHICLE_TYPE (
    VEHICLE_TYPE_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(30),
    MODEL VARCHAR(30)
);
 
CREATE TABLE VEHICLE (
    VIN VARCHAR(17) PRIMARY KEY,
    VEHICLE_TYPE_ID INT,
    COLOR VARCHAR(20),
    YEAR INT,
    MILEAGE DOUBLE,
    IMAGE VARCHAR(200),
    FOREIGN KEY (VEHICLE_TYPE_ID) REFERENCES VEHICLE_TYPE(VEHICLE_TYPE_ID)
);
 
CREATE TABLE INVENTORY (
    INVENTORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    VIN VARCHAR(17) NOT NULL,
    QUANTITY INT,
    PRICE DOUBLE,
    FOREIGN KEY (VIN) REFERENCES VEHICLE(VIN)
);